/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilitarios.ConectaBanco;

/**
 *
 * @author claitoncorrea
 */
public class CadastroEstados extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();

    /**
     * Creates new form CadastroEstados
     */
    public CadastroEstados() {
        initComponents();
        conecta.conexao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelEstados = new javax.swing.JPanel();
        txcodigo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textocodigo = new javax.swing.JTextField();
        textonome = new javax.swing.JTextField();
        textosigla = new javax.swing.JTextField();
        btadd = new javax.swing.JButton();
        btmodify = new javax.swing.JButton();
        btview = new javax.swing.JButton();
        btclear = new javax.swing.JButton();
        btsave = new javax.swing.JButton();
        btout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaestados = new javax.swing.JTable();
        PainelBt = new javax.swing.JPanel();
        btprimeiro = new javax.swing.JButton();
        btultimo = new javax.swing.JButton();
        btproximo = new javax.swing.JButton();
        btanterior = new javax.swing.JButton();
        btvoltartela = new javax.swing.JButton();
        concluido = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Estados");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.UTILITY);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        PainelEstados.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 0), new java.awt.Color(204, 204, 0)));

        txcodigo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txcodigo.setText("Código");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Sigla");

        textocodigo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        textocodigo.setToolTipText("Insira o Código do Estado \"Sómente Numeros\"");
        textocodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        textocodigo.setDragEnabled(false);
        textocodigo.setEnabled(false);
        textocodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textocodigoActionPerformed(evt);
            }
        });

        textonome.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        textonome.setToolTipText("Insira o Nome do Estado");
        textonome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        textonome.setEnabled(false);
        textonome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textonomeActionPerformed(evt);
            }
        });

        textosigla.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        textosigla.setToolTipText("Insira a Sigla do Estado");
        textosigla.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        textosigla.setEnabled(false);
        textosigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textosiglaActionPerformed(evt);
            }
        });

        btadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        btadd.setToolTipText("Novo Estado");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btmodify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Editar.png"))); // NOI18N
        btmodify.setToolTipText("Modificar");
        btmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodifyActionPerformed(evt);
            }
        });

        btview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        btview.setToolTipText("Visualizar");
        btview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btviewMouseClicked(evt);
            }
        });
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });

        btclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Lixeira_1.png"))); // NOI18N
        btclear.setToolTipText("Excluir");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });

        btsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        btsave.setToolTipText("Salvar Alterações");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        btout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.png"))); // NOI18N
        btout.setToolTipText("Fechar e Voltar");
        btout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoutMouseClicked(evt);
            }
        });
        btout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoutActionPerformed(evt);
            }
        });

        tabelaestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaestados.setToolTipText("Tabela de Estados");
        jScrollPane1.setViewportView(tabelaestados);

        PainelBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 211, 61)));

        btprimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Anterior1.png"))); // NOI18N
        btprimeiro.setToolTipText("Primeiro Registro");
        btprimeiro.setEnabled(false);
        btprimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprimeiroActionPerformed(evt);
            }
        });

        btultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/proximo1.png"))); // NOI18N
        btultimo.setToolTipText("Ultimo Registro");
        btultimo.setEnabled(false);
        btultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btultimoActionPerformed(evt);
            }
        });

        btproximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Avancar1.png"))); // NOI18N
        btproximo.setToolTipText("Proximo");
        btproximo.setEnabled(false);
        btproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btproximoActionPerformed(evt);
            }
        });

        btanterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Voltar1.png"))); // NOI18N
        btanterior.setToolTipText("Anterior");
        btanterior.setEnabled(false);
        btanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btanteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBtLayout = new javax.swing.GroupLayout(PainelBt);
        PainelBt.setLayout(PainelBtLayout);
        PainelBtLayout.setHorizontalGroup(
            PainelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBtLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btprimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btproximo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelBtLayout.setVerticalGroup(
            PainelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBtLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PainelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btproximo)
                    .addComponent(btanterior)
                    .addComponent(btultimo)
                    .addComponent(btprimeiro))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btvoltartela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SetaEsquerda_1.png"))); // NOI18N
        btvoltartela.setToolTipText("Voltar");
        btvoltartela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvoltartelaActionPerformed(evt);
            }
        });

        concluido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Concluido.png"))); // NOI18N
        concluido.setToolTipText("Concluir");
        concluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluidoActionPerformed(evt);
            }
        });

        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancelar_1.png"))); // NOI18N
        btcancelar.setToolTipText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelEstadosLayout = new javax.swing.GroupLayout(PainelEstados);
        PainelEstados.setLayout(PainelEstadosLayout);
        PainelEstadosLayout.setHorizontalGroup(
            PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEstadosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelEstadosLayout.createSequentialGroup()
                        .addComponent(btadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmodify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btclear)
                        .addGap(28, 28, 28)
                        .addComponent(PainelBt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btout)
                        .addContainerGap())
                    .addGroup(PainelEstadosLayout.createSequentialGroup()
                        .addGroup(PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txcodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelEstadosLayout.createSequentialGroup()
                                .addComponent(textocodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PainelEstadosLayout.createSequentialGroup()
                                .addComponent(textonome, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textosigla, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(concluido)
                                .addGap(57, 57, 57))))))
            .addGroup(PainelEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(PainelEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btvoltartela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelEstadosLayout.setVerticalGroup(
            PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btvoltartela)
                .addGap(94, 94, 94)
                .addGroup(PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(PainelEstadosLayout.createSequentialGroup()
                        .addGroup(PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txcodigo)
                            .addComponent(textocodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textonome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(textosigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concluido)
                    .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btclear, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btadd))
                    .addComponent(btmodify, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btsave, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btview, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PainelBt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(201, 194, 63));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Cadastro de Estados");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelEstados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(PainelEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(797, 671));
    }// </editor-fold>//GEN-END:initComponents


    private void textonomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textonomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textonomeActionPerformed

    private void textosiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textosiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textosiglaActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed

        try {
            java.sql.PreparedStatement pst = conecta.conn.prepareStatement("insert into Estados (nome_estado,sigla_estado)values(?,?)");
            if (textonome.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Não é permitido campo vazio. Digite o nome do Estado para salvar!");
            } else {
                pst.setString(1, textonome.getText());
            }
            if (textosigla.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Não é permitido campo vazio. Digite a sigla do estado para salvar!");
            } else {
                pst.setString(2, textosigla.getText());
            }
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Gravado com sucesso!");
            textonome.setText("");
            textosigla.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum dado foi gravado. Insira os valores corretos e tente novamente!");
            textonome.setText("");
            textosigla.setText("");
        }
        textonome.setEnabled(false);
        textosigla.setEnabled(false);
        btsave.setVisible(false);
        btadd.setVisible(true);
        btview.setVisible(true);
        txcodigo.setVisible(true);
        textocodigo.setVisible(true);
        btclear.setVisible(false);
        PainelBt.setVisible(false);
        btmodify.setVisible(false);

    }//GEN-LAST:event_btsaveActionPerformed

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btviewActionPerformed

    private void btoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoutMouseClicked
        dispose();
    }//GEN-LAST:event_btoutMouseClicked

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        textonome.setEnabled(true);
        textosigla.setEnabled(true);
        btsave.setVisible(true);
        btview.setVisible(false);
        btadd.setVisible(false);
        textocodigo.setText("");
        textonome.setText("");
        textosigla.setText("");
        btvoltartela.setVisible(true);
        txcodigo.setVisible(false);
        textocodigo.setVisible(false);
        btclear.setVisible(false);
        PainelBt.setVisible(false);

    }//GEN-LAST:event_btaddActionPerformed

    private void btviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btviewMouseClicked
        try {
            conecta.executaSQLQuery("select * from Estados");
            conecta.rs.first();
            textocodigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            textonome.setText(conecta.rs.getString("nome_estado"));
            textosigla.setText(conecta.rs.getString("sigla_estado"));
            btsave.setVisible(false);
            btclear.setVisible(true);
            btmodify.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na leitura do Banco de Dados");
        }

        PainelBt.setVisible(true);
        btprimeiro.setEnabled(true);
        btultimo.setEnabled(true);
        btanterior.setEnabled(true);
        btproximo.setEnabled(true);
        btmodify.setEnabled(true);
        btvoltartela.setVisible(true);
        btview.setVisible(false);

    }//GEN-LAST:event_btviewMouseClicked

    private void textocodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textocodigoActionPerformed

    }//GEN-LAST:event_textocodigoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    
        PainelBt.setVisible(false);
        btmodify.setVisible(false);
        btsave.setVisible(false);
        btclear.setVisible(false);
        btvoltartela.setVisible(false);
        concluido.setVisible(false);
        btcancelar.setVisible(false);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        try {
            java.sql.PreparedStatement pst = conecta.conn.prepareStatement("delete from Estados where sigla_estado=?");
            pst.setString(1, textosigla.getText().toString());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Dados excluidos com Sucesso");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na exclusão");
        }
        btmodify.setVisible(false);
        btclear.setVisible(false);
        textosigla.setText("");
        textosigla.setEnabled(false);
        textocodigo.setText("");
        textonome.setText("");
        textosigla.setText("");
        PainelBt.setVisible(false);
        btview.setVisible(true);

    }//GEN-LAST:event_btclearActionPerformed

    private void btprimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprimeiroActionPerformed

        try {
            conecta.executaSQLQuery("select * from Estados");
            conecta.rs.first();
            textocodigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            textonome.setText(conecta.rs.getString("nome_estado"));
            textosigla.setText(conecta.rs.getString("sigla_estado"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na leitura do Banco de Dados");
        }
    }//GEN-LAST:event_btprimeiroActionPerformed

    private void btproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btproximoActionPerformed
        try {
          
            conecta.rs.next();
            textocodigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            textonome.setText(conecta.rs.getString("nome_estado"));
            textosigla.setText(conecta.rs.getString("sigla_estado"));

        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_btproximoActionPerformed

    private void btultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btultimoActionPerformed

        try {
            conecta.executaSQLQuery("select * from Estados");
            conecta.rs.last();
            textocodigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            textonome.setText(conecta.rs.getString("nome_estado"));
            textosigla.setText(conecta.rs.getString("sigla_estado"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na leitura do Banco de Dados");
        }

    }//GEN-LAST:event_btultimoActionPerformed

    private void btanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btanteriorActionPerformed

        try {
            
            conecta.rs.previous();
            textocodigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            textonome.setText(conecta.rs.getString("nome_estado"));
            textosigla.setText(conecta.rs.getString("sigla_estado"));

        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_btanteriorActionPerformed

    private void btvoltartelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvoltartelaActionPerformed
        btadd.setVisible(true);
        btview.setVisible(true);
        btvoltartela.setVisible(false);
        txcodigo.setVisible(true);
        textocodigo.setVisible(true);
        btsave.setVisible(false);
        btclear.setVisible(false);
        PainelBt.setVisible(false);
        textocodigo.setText("");
        textonome.setText("");
        textosigla.setText("");
        textonome.setEnabled(false);
        textosigla.setEnabled(false);
        btmodify.setVisible(false);
        
    }//GEN-LAST:event_btvoltartelaActionPerformed

    private void concluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluidoActionPerformed
        
        try {
            java.sql.PreparedStatement pst = conecta.conn.prepareStatement("update Estados set nome_estado=?,sigla_estado=? where id_estado =?");
            pst.setString(1, textonome.getText());
            pst.setString(2, textosigla.getText());
            pst.setInt(3, Integer.parseInt(textocodigo.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
        
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro com o Banco de Dados! \n Erro: "+ex.getMessage());
        }
        
        btvoltartela.setVisible(true);
        btadd.setVisible(true);
        btview.setVisible(true);
        txcodigo.setVisible(true);
        btclear.setVisible(true);
        PainelBt.setVisible(true);
        try {
            conecta.executaSQLQuery("select * from Estados");
            conecta.rs.first();
            textocodigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            textonome.setText(conecta.rs.getString("nome_estado"));
            textosigla.setText(conecta.rs.getString("sigla_estado"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na leitura do Banco de Dados");
        }
        textonome.setEnabled(false);
        textosigla.setEnabled(false);
        btmodify.setVisible(true);
        concluido.setVisible(false);
        btcancelar.setVisible(false);
    }//GEN-LAST:event_concluidoActionPerformed

    private void btmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodifyActionPerformed
        btvoltartela.setVisible(false);
        textonome.setEnabled(true);
        textosigla.setEnabled(true);
        concluido.setVisible(true);
        btadd.setVisible(false);
        btmodify.setVisible(false);
        btsave.setVisible(false);
        btview.setVisible(false);
        btclear.setVisible(false);
        PainelBt.setVisible(false);
        btcancelar.setVisible(true);
        
    }//GEN-LAST:event_btmodifyActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        btvoltartela.setVisible(true);
        btadd.setVisible(true);
        btview.setVisible(true);
        txcodigo.setVisible(true);
        btclear.setVisible(true);
        PainelBt.setVisible(true);
        try {
            conecta.executaSQLQuery("select * from Estados");
            conecta.rs.first();
            textocodigo.setText(String.valueOf(conecta.rs.getInt("id_estado")));
            textonome.setText(conecta.rs.getString("nome_estado"));
            textosigla.setText(conecta.rs.getString("sigla_estado"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha na leitura do Banco de Dados");
        }
        textonome.setEnabled(false);
        textosigla.setEnabled(false);
        btmodify.setVisible(true);
        concluido.setVisible(false);
        btcancelar.setVisible(false);
        
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEstados().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBt;
    private javax.swing.JPanel PainelEstados;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btanterior;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btclear;
    private javax.swing.JButton btmodify;
    private javax.swing.JButton btout;
    private javax.swing.JButton btprimeiro;
    private javax.swing.JButton btproximo;
    private javax.swing.JButton btsave;
    private javax.swing.JButton btultimo;
    private javax.swing.JButton btview;
    private javax.swing.JButton btvoltartela;
    private javax.swing.JButton concluido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaestados;
    private javax.swing.JTextField textocodigo;
    private javax.swing.JTextField textonome;
    private javax.swing.JTextField textosigla;
    private javax.swing.JLabel txcodigo;
    // End of variables declaration//GEN-END:variables
}
