/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import utilitarios.ConectaBanco;

/**
 *
 * @author claitoncorrea
 */
public class Principal extends javax.swing.JFrame {
    ConectaBanco conecta = new ConectaBanco();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        conecta.conexao();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuprincipal = new javax.swing.JMenuBar();
        menucadastros = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menucompra = new javax.swing.JMenu();
        menuvenda = new javax.swing.JMenu();
        menurelatorio = new javax.swing.JMenu();
        menusair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas");

        menucadastros.setText("Cadastros");
        menucadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastrosActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Estados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menucadastros.add(jMenuItem1);

        jMenuItem2.setText("Cidades");
        menucadastros.add(jMenuItem2);

        jMenuItem3.setText("Bairro");
        menucadastros.add(jMenuItem3);

        jMenuItem4.setText("Telefones");
        menucadastros.add(jMenuItem4);

        jMenuItem5.setText("Clientes");
        menucadastros.add(jMenuItem5);

        jMenuItem6.setText("Fornecedores");
        menucadastros.add(jMenuItem6);

        jMenuItem7.setText("Produtos");
        menucadastros.add(jMenuItem7);

        menucompra.setText("Compra");
        menucadastros.add(menucompra);

        menuprincipal.add(menucadastros);

        menuvenda.setText("Venda");
        menuprincipal.add(menuvenda);

        menurelatorio.setText("Relatórios");
        menuprincipal.add(menurelatorio);

        menusair.setText("Sair");
        menusair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menusairMouseClicked(evt);
            }
        });
        menuprincipal.add(menusair);

        setJMenuBar(menuprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(843, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       CadastroEstados estados;
       estados = new CadastroEstados();
       estados.setVisible(true);
       //estados.setLocationRelativeTo(null);
       estados.setFocusable(true);
       
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menusairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menusairMouseClicked
        conecta.desconecta();
        System.exit(0);
        
    }//GEN-LAST:event_menusairMouseClicked

    private void menucadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastrosActionPerformed
        
    }//GEN-LAST:event_menucadastrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Principal().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu menucadastros;
    private javax.swing.JMenu menucompra;
    private javax.swing.JMenuBar menuprincipal;
    private javax.swing.JMenu menurelatorio;
    private javax.swing.JMenu menusair;
    private javax.swing.JMenu menuvenda;
    // End of variables declaration//GEN-END:variables
}
